
services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - DataBase
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=docker-compose
#      - SPRING_DATASOURCE_PASSWORD=docker-compose
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  DataBase:
    image: 'postgres:latest'
    container_name: OctopusDataBase
    environment:
      - POSTGRES_USER=docker-compose
      - POSTGRES_PASSWORD=docker-compose
      - POSTGRES_PORT=5432
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/postgres
    ports:
      - 5432:5432
    expose:
      - 5432